PyAV-Org/PyAV

- av/audio/layout.pyx
> Added simplified entries for channel counts greater than 8

- docs/installation.rst
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mikeboers/pyav/198)
> Fix missing Ubuntu 14.04 dependancy

- av/packet.pyx
- av/stream.pyx
> ability to set pts and streamid

- av/logging.pyx
- av/packet.pyx
- av/subtitles/subtitle.pyx
- av/video/format.pyx
- av/video/frame.pxd
- av/video/frame.pyx
- include/libavcodec/avcodec.pxd
- include/libavutil/avutil.pxd
I'd like to fix a couple more warnings before merging.
> Eliminate some compilation warnings (#379)

- av/audio/resampler.pyx
- av/video/frame.pyx
This PR fixes a few more compiler warnings about constness
> Const warnings

- CHANGELOG.rst
- av/container/input.pyx
- av/stream.pyx
- tests/test_seek.py
> Container.seek(time, stream=foo) for specifying time_base of a stream.

- av/logging.pyx
Occasionally the logging handler locks up, which can be reproduced by
repeatedly running the test suite. Moving log emission out of the
skip_lock context manager seems to fix the problem.
> Avoid deadlocking the log handler

- av/container/core.pxd
- av/container/core.pyx
- av/container/input.pyx
- include/libavformat/avformat.pxd
- tests/test_timeout.py
This is an alternative take on #316 using Python's time.time().
> Add support for open and read timeouts

- Makefile
- av/codec/context.pyx
- av/frame.pxd
- av/frame.pyx
- av/sidedata/motionvectors.pxd
- av/sidedata/motionvectors.pyx
- av/sidedata/sidedata.pxd
- av/sidedata/sidedata.pyx
- av/video/codeccontext.pyx
- av/video/frame.pxd
- av/video/frame.pyx
- include/libav.pxd
- include/libavcodec/avcodec.pxd
- include/libavutil/frame.pxd
- include/libavutil/motion_vector.pxd
- scratchpad/sidedata.py
- tests/test_decode.py
- tests/test_enums.py
I wasn't too keen on #557 (because it appeared to be tailored to a specific use-case), but it did show me how to work with side data, so I whipped this together.
Thoughts, anyone?
> Expose Frame Sidedata

- scripts/activate.sh
- scripts/build-deps
The library name is always ffmpeg nowadays.
> [build] remove PYAV_LIBRARY_NAME

- scripts/fetch-ffmpeg
The following were added:
- libaom
- libass
- libbluray
- libdav1d
- libwavpack
- libxvid
> [build] update FFmpeg build with additional libraries

- av/codec/context.pyx
- tests/test_codec_context.py
This is just #748 with an additional test
> Expose codec_context.codec_tag (fixes: #741)

- tests/common.py
- tests/test_audioframe.py
- tests/test_videoframe.py
Show the differences between the arrays to make debugging easier.
> [tests] make ndarray comparisons more explicit

- av/logging.pyx
`mov_read_trak()` and `mov_read_trun()` generate a lot of `AV_LOG_TRACE`
logs, which are ultimately thrown away. However, `log_callback()` still
formats and processes them. This causes `av_log()` to - at least in some
cases I observed with perf record - to take 97% of
`avformat_open_input()` run time. Improve this by returning from
`log_callback()` early when a log is obviously not needed.
> Avoid unnecessary vsnprintf() calls in log_callback()

- scripts/fetch-vendor.json
This updates several packages to fix security vulnerabilities.
> [package] update FFmpeg binaries for wheels (fixes: #901)

- tests/test_codec_context.py
- tests/test_encode.py
- flush audio encoders
- reset the picture type for video encoding
- stop gratuitously clearing pts
> [tests] reduce the number of warnings

- av/container/core.pxd
- av/container/core.pyx
- av/container/pyio.pxd
- av/container/pyio.pyx
This was extracted from PR https://github.com/PyAV-Org/PyAV/pull/718
> Move Python I/O code to a PyIOFile class

- av/stream.pyx
- docs/api/codec.rst
- docs/api/stream.rst
- docs/conf.py
- tests/requirements.txt
Also remove a reference to the obsolete Stream.seek() method.
See: #913
> [docs] fix build by pinning sphinx < 4.4

- av/container/output.pyx
- tests/test_python_io.py
We must only ever call av_write_trailer *once*, otherwise we get a
segmentation fault. Therefore no matter whether it succeeds or not
we must absolutely set self._done.
Also we need to be more careful when closing the streams' CodecContext:
- It's too late to iterate over the streams in `__dealloc__` as Python
object destruction may have already started.
- We must not error if there is not CodecContext or if the CodecContext
has already been closed by the user.
> Ensure av_write_trailer is only called once (fixes: #613)

- docs/overview/installation.rst
- scripts/fetch-vendor.json
This updates several packages to fix security vulnerabilities and adds
support for vpx.
> [package] update FFmpeg binaries for wheels (fixes: #921)

- tests/test_file_probing.py
- test all attributes for every media type
- sort tested attributes alphabetically
- move multi-valued tests
> [tests] uniformize file probing tests

- scripts/fetch-vendor.json
Fix vpx flags for macos, see https://github.com/PyAV-Org/pyav-ffmpeg/pull/63
> [package] update FFmpeg binaries

- .github/workflows/tests.yml
Use ffmpeg binary from ~https://github.com/BtbN/FFmpeg-Builds/releases~ pyav-ffmpeg.
> Add CI test for Win ffmpeg 4.4

- av/container/core.pyx
- av/container/output.pyx
> Add documentation

- av/frame.pyx
- av/packet.pyx
> Packet set is keyframe

- av/sidedata/sidedata.pyx
We only support ffmpeg 5 or greater.
> Remove obsolete comments

- av/filter/graph.pyx
- docs/index.rst
We also remove some unnecessary newlines.
> Remove commented-out code in graph

- av/audio/stream.pyi
See https://github.com/PyAV-Org/PyAV/pull/1317
> Add codec_context typing for AudioStream

- docs/api/codec.rst
I missed the docs update in #1382
> Add flush_buffers to CodecContext docs

- av/container/streams.pxd
- av/container/streams.pyi
- av/container/streams.pyx
- docs/api/attachments.rst
- docs/api/stream.rst
- include/libavformat/avformat.pxd
- tests/test_streams.py
> Add `best()` to StreamContainer

- tests/test_audiofifo.py
- tests/test_bitstream.py
- tests/test_codec_context.py
- tests/test_colorspace.py
- tests/test_containerformat.py
- tests/test_decode.py
- tests/test_encode.py
- tests/test_enums.py
- tests/test_seek.py
- tests/test_streams.py
- tests/test_videoformat.py
Works better with mypy. `assert`s work equally well since we're using pytest now.
> Replace self.assertEqual with `assert` statement

- Makefile
- tests/common.py
- tests/test_audioformat.py
- tests/test_audioframe.py
- tests/test_audiolayout.py
- tests/test_audioresampler.py
- tests/test_bitstream.py
- tests/test_codec.py
- tests/test_codec_context.py
- tests/test_colorspace.py
- tests/test_containerformat.py
- tests/test_deprecation.py
- tests/test_dictionary.py
- tests/test_encode.py
- tests/test_enums.py
- tests/test_errors.py
- tests/test_python_io.py
- tests/test_videoframe.py
We don't need to put tests in a class anymore. I also sprinkled some type hints here and there. Left a few because the commit would be too big otherwise.
> Make tests more idiomatic for pytest

- av/container/input.pyx
- av/container/output.pyx
This eventually applies the "workaround" automatically
> Fix for #1599

- MANIFEST.in
> Ensure to add the loudnorm_impl.h in the pypi source distribution

- docs/overview/installation.rst
The tests/requirements.txt file was removed in #1475
> remove tests/requirements.txt mention

- scripts/build-deps
update cuda config flag to "--enable-cuda-nvcc"  as per [Video Codec SDK v13.0](https://docs.nvidia.com/video-technologies/video-codec-sdk/13.0/ffmpeg-with-nvidia-gpu/index.html)
> update cuda config flags

- av/audio/format.pyx
> Fix doc typo for AudioFormat.is_packed
