PyAV-Org/PyAV

av/audio/stream.pyx
av/container.pyx

Hi, I ran into this issue when trying to encode files with audio track. Took the same approach as you did in VideoStream.encode.
I'm wondering if coded_frame will ever be set in case of audio frames. Seems like coded_frame is referenced by video/image codecs only..
http://ffmpeg.org/doxygen/trunk/structAVCodecContext.html#afdebc347b4f74e0b9271ff37cabc96e8

Fix: AudioStream._codec_context.coded_frame can be None, causing SEGV

---

Makefile
av/__init__.py
scripts/generate_video.py
setup.py

Patch that makes it possible to compile the project on windows using the [mingw64 compiler](http://mingw-w64.yaxm.org/doku.php).
I've only tested with the 32-bit version of the compiler since I'm only using the official 32-bit version of python 2.7 on that platform.
I imaging this patch will have to be reworked a lot before you feel it could be considered, since it *smells* a bit forced atm. However I've tried to group the windows specific parts into one conditional per file, to make it easy to spot what parts are "generic" and which are very platform specific.
The patch requires the user to put the compiled libav libraries and their two mingw dll dependencies into the av-directory, so that your cython wrappers can find them at runtime. If the user forgets to do that, a "helpful" …

fix for building on windows using mingw64-32

---

setup.py

This removes the use of `ctypes` to discover what functions are available. Instead, it uses the same C compiler that Python would end up using to compile the modules in order to build and link tiny test executables and discover if those functions exist.
This also allows for detecting members of structures, so we can safely implement deprecated members.
This breaks our Window's build (temporarily, and only because I can't maintain it).
Any thoughts?

Use distutils.ccompiler to test for functions and structure members

---

av/container.pyx
setup.py

PyAV will throw OverflowError: value too large to convert to int when opening a python file object larger than 2GB, but open by filename is ok.
I found that pyio_seek_gil should return int64_t instead of int for opening a large file.
Sorry for wrong insert about setup.py, this pull request has reseted that commit.

pyio seek's return type should be int64_t

---

docs/examples.rst
docs/index.rst

I'm trying to start using PyAV to replace a bunch of ugly shell calls to ffmpeg. It's working great so far, but I've mostly been learning the library by reading your test cases.
I was wondering if some of the simpler ones could be made into an ``examples`` docs page. This pull is for ``tests/test_encoding.py`` which is a good example of how to write a movie from numpy/PIL.
I'd be happy to add a few more if you think this is a good idea.

Add an example of writing a movie from numpy

---

appveyor.yml

@mikeboers I noticed the Appveyor build to fail for no apparent reason. To save us from corrupt downloads, I changed the test recipe, pulling in `ffmpeg` and `msinttypes` binaries from conda-forge. This does limit the ffmpeg version to 2.8.6, as that is the only version currently on conda.

Rebase Appveyor build on conda

---

appveyor.yml

A newer FFMPEG version is available from conda-forge, so that we can easily update the tests. 
I additionally removed Python 3.3 and added 3.6 to the tests.

Update appveyor ffmpeg version

---

av/frame.pyx
include/libavcodec/avcodec.pxd

`int AVFrame::flags` is a collection of `AV_FRAME_FLAGS`
Added property `is_corrupt` to class Frame that checks
if `AV_FRAME_FLAG_CORRUPT` is set which would then indicate that:
```
The frame data may be corrupted, e.g.
due to decoding errors.
```

Expose frame corruption check.

---

av/container/core.pxd
av/container/core.pyx
av/container/input.pyx
av/container/output.pyx
av/stream.pyx
av/utils.pxd
av/utils.pyx

For writing, and for reading on Python 3, the default codec changes
from ASCII to UTF-8. In Python 2, the default behavior remains to not
perform decoding on reading, but this can be overridden by explicitly
specifying an encoding. This change applies to both container and
stream metadata.
fixes #59

Support specifying metadata character encoding

---

av/container/core.pxd
av/container/core.pyx
include/libavformat/avformat.pxd
tests/test_codec_context.py
tests/test_encode.py
tests/test_options.py
tests/test_random_input.py

[=] fix segfault resulting from incorrect FFMPEG structures deallocation
[=] fix some tests to be runnable under python3
[+] add test for correct (segfault free) opening of file with random data
[=] fix ContainerProxy.seek behaviour for integers more then 2**31 with 32bit CPython

Fix SegFault resulting from incorrect FFMPEG structures deallocation

---

av/container/core.pyx

metadata_encoding needs to be set before the ContainerProxy is
instantiated, because it's read in the proxy's initializer.
Fixes mikeboers/PyAV#265

Fix Container property initialization order

---

README.md
setup.cfg

Hi Mike (or anyone reading this),
since the new PyPI supports Markdown READMEs, I added the appropriate settings to `setup.cfg` so that the PyPI page actually displays something.
I also added some project links (that are displayed on the left-hand side of https://pypi.org/project/av/), currently there's only **Homepage** but I also added:
- **Bug Reports** with a link to the GitHub issue tracker
- **Documentation** with a link to the docs
- **Feedstock** with a link to the `av` conda-forge feedstock
I also added a `license` key to the metadata, as for now https://shields.io fails to extract the license from the classifiers. This means the license badge for `av`, which currently is:
should look like this once the PR is merged:

Add project metadata to PyPI.org webpage

---

scripts/activate.sh

When do `bash scripts/build-deps`,the script will print below errors:
`+++ python -c '
from __future__ import print_function
import sys
import platform
print("{}{}.{}".format(platform.python_implementation().lower(), *sys.version_info[:2]))
'
File "<string>", line 2
from __future__ import print_function
^
IndentationError: unexpected indent`
This PR is to fix this issue.

Fix IndentationError(unexpected indent) in activate.sh

---

appveyor.yml
av/container/core.pxd
av/container/core.pyx
scripts/activate.sh
tests/test_container.py

The Python 2.7 builds are bombing:
ImportError: No module named 'setuptools'

Fix travis and appveyor continuous integration

---

tests/test_python_io.py

This fixes a warning due to file descriptors not being closed in two
Python I/O tests.

Close file descriptors in tests

---

av/video/codeccontext.pyx

We are guaranteed to be handed an AVCodecContext* in the constuctor.
AudioCodecContext doesn't have these kind of checks. This is most likely
a left-over from the refactoring that specialized CodecContext classes.

Remove 'if self.ptr' checks from VideoCodecContext

---

av/container/output.pyx
tests/test_encode.py

OutputContainer.add_stream() nicely initialises some default options
both for audio and video streams. Unfortunately, we wrap the low-level
AVCodecContext and AVStream into Python objects before we finish
initialising them.
For video streams this results in the crucial "pix_fmt" being cleared
inside VideoCodecContext._init, which leads to a crash during encoding
if the user does not set "pix_fmt" (again) themselves:
Assertion desc failed at libswscale/swscale_internal.h:674
With this PR we finish the CodecContext initialization *before* we start
wrapping the stream into a Python object.
As a result of this fix, all video encoding examples can be simplified
to remove this:
stream.pix_fmt = 'yuv420p'

Defer wrapping output stream into Python object

---

av/codec/codec.pyx
av/codec/context.pyx
av/filter/pad.pyx
av/stream.pyx
av/utils.pxd
av/utils.pyx
include/libavutil/avutil.pxd

Now that we have dropped libav, we can use this function instead of
defining our own.

Use av_get_media_type_string

---

CHANGELOG.rst
av/buffer.pyx
av/packet.pyx
av/plane.pyx
examples/gen_rgb_rotate.py
tests/test_encode.py
tests/test_videoframe.py

We provide the following backwards compatibility aliases
- Packet.update_buffer
- Plane.update_buffer and Plane.update_from_string

Rename Buffer.update_buffer to Buffer.update

---

.travis.yml
CHANGELOG.rst
av/audio/fifo.pyx
av/codec/context.pyx
docs/installation.rst
include/libavcodec/avcodec.pxd
include/libavcodec/avcodec.pyav.h
setup.py

Only use frame.pts, frame.pkt_pts is obsolete.
Also stop detecting the presence of av_frame_get_best_effort_timestamp,
it's guaranteed to be present now that we require ffmpeg >= 3.0. Not
that we use it anyway..

Stop using deprecated pkt_pts

---

av/audio/codeccontext.pyx
av/codec/context.pxd
av/codec/context.pyx
av/packet.pyx
av/stream.pyx
av/subtitles/codeccontext.pyx
av/video/codeccontext.pyx
include/libav.pxd
include/libavcodec/avcodec.pxd
include/libavcodec/avcodec.pyav.h
scratchpad/memleak.py
setup.py
tests/test_subtitles.py

Since FFmpeg 3.1, the preferred mechanism for encoding / decoding audio and video is using a send / receive mechanisms instead of calling avcodec_xxx_encode and avcodec_xxx_decode methods.
Now that our baseline is FFmpeg 3.2 we can remove the legacy code, which fixes a number of deprecation warnings.

Always use send / recv mechanism

---

av/utils.pyx

On Python 2, the previous code did not systematically perform the
decoding depending on whether or not an encoding was given.
With this PR we align the Python 2 behaviour on the sane behaviour of
Python 3. This also avoids a compilation warning on Python 3 were we
tested "str is str".

Deterministically perform bytes -> str decoding

---

av/codec/codec-shims.c
av/codec/codec.pyx
av/filter/filter-shims.c
av/filter/filter.pyx
av/format-shims.c
av/format.pyx

The current code spews warnings both for old and new FFmpegs. This PR fixes the warnings by:
- aligning function prototypes on FFmpeg 4.0's (fixes new FFmpegs)
- adding the necessary casts for older FFmpegs
This completes the work done in #412.

Fix const warnings on iterator shims

---

av/video/frame.pxd
av/video/frame.pyx
tests/test_videoframe.py

The previous implementation of .to_image() only worked if the
VideoFrame's line size matched the image width.

Fix VideoFrame.to_image / .from_image alignment

---

CHANGELOG.rst
av/container/output.pyx
include/libavcodec/avcodec.pxd

av_packet_clone both allocates an AVPacket structure and makes a new
reference to the underlying buffer. av_interleaved_write_frame only calls
av_packet_unref when it's done with the packet, it doesn't actually free it.

Fix memory leak in OutputContainer.mux_one (fixes: #431)

---

CHANGELOG.rst
av/container/core.pyx

When using "custom I/O", avformat_close_input will not call avio_close
so it is up to us to clean up.

Fix memory leak with Python I/O (fixes: #317)

---

av/container/streams.pyx
av/stream.pyx
docs/api/stream.rst
tests/test_file_probing.py

For consistency with other APIs we make `start_time` return None if
unknown.

Add docstrings for Stream properties and methods.

---

include/libavcodec/avcodec.pyav.h

We explicitly fail the build as early as possible if a build is
attempted against an unsupported FFmpeg version. This gives users a
clear indication of what is wrong instead of triggering obscure
compiler errors about missing functions or struct members.
We also remove the reference to PYAV_HAVE_FFMPEG which is not defined
anymore.

Assert PyAV is built against a compatible FFmpeg (fixes: #401)

---

av/data/stream.pyx
av/stream.pyx
tests/test_file_probing.py

This fleshes out the file probing tests to also cover data and subtitle streams.

Add tests for data and subtitle file probing

---

av/data/stream.pyx

Its signature does not match Stream.seek, leading to the bug mentioned
in #299.
Furthermore, this method does nothing, where as the base Stream.seek
should work for any kind of stream.
(Re-PR because AppVeyor doesn't like what I did.)

Remove DataStream.seek override (fixes: #299)

---

av/datasets.py

Our dataset items are referenced using forward slahes, but Windows
expects back slashes for paths.

Replace path separators when constructing dataset item path

---

av/container/core.pxd
av/container/core.pyx
av/container/input.pxd
av/container/input.pyx
av/container/output.pyx
av/container/pyio.pyx
av/stream.pxd
av/stream.pyx
scratchpad/container-gc.py

This was a layer that was once required for garbage collection due to the
cyclic relationships between containers and streams. Newer Cythons seem to deal
with it better.

Remove ContainerProxy.

---

av/container/core.pyx
av/container/input.pyx
av/container/output.pyx

This is useful to explicitly close resources such as webcams, without having to wait for the GC to kick in.

Make it possible to close input container

---

appveyor.yml
setup.cfg
setup.py
tests/requirements.txt

Vanilla "unittest" is good enough since Python 2.7 / 3.2.

Stop using nose to run tests

---

av/container/core.pyx

This is useful when working with file-like objects that go to
Amazon S3, because it makes it possible to reduce the amount of
requests.

Make input/output buffer size configurable

---

av/container/core.pyx
tests/test_container.py

This allows us to do:
```python
with av.open('some_file.mp4') as container:
...
```

Allow av.open to be used as a context manager

---

av/container/core.pyx
av/container/input.pyx
av/container/output.pyx

The Cython documentation indicate that calling Python methods inside
__dealloc__ is not safe. While we seem to get away with it on CPython,
PyPy is not so forgiving.

Don't call Python methods when deallocating a container

---

av/audio/frame.pyx
av/frame.pxd
av/frame.pyx
av/video/frame.pyx

This avoids reference loops which make it hard for the garbage collector
to free AudioFrame and VideoFrame instances.

Make audio / video planes property lazy

---

.travis.yml
CHANGELOG.rst
av/logging.pyx
av/video/frame.pyx
docs/caveats.rst
docs/index.rst
include/libavutil/avutil.pxd

Users can disable the logging system, which is the harder one the avoid.

Subinterpreters

---

av/codec/context.pxd
av/codec/context.pyx
docs/cookbook/basics.rst
examples/basics/parse.py
tests/test_codec_context.py

Another option is to create a separate `CodecParser` object. While that feels more flexible, etc., when would someone really want to have the parser in isolation from the context?
I'll answer my own question: when someone doesn't care to decode at the moment.
I'm going to go isolate it.

Codec parsing

---

av/video/frame.pxd
av/video/frame.pyx
av/video/reformatter.pyx
include/libswscale/swscale.pxd

Early implement for #577 
I've been using this indoor for months. My main hesitation to upstream this was its change to API.
A new argument with default value was added to `VideoFrame._reformat`. It seems that argument with default value was never use in `cdef` in this project, but this is probably the only way not to break existing code.
Please consider this as a proposal. I would like to update this PR to meet up with an updated API design.

Expose swscale flags

---

av/video/frame.pyx
tests/test_videoframe.py

`yuvj420p` has the same shape as `yuv420p`. The difference in color ranges: 
- `yuv420p` according to rec 709 (https://en.wikipedia.org/wiki/Rec._709#Digital_representation) has a nominal range of [16..235] for Y channel and CB and CR channels have a nominal range of [16..240]. rec 601 has limited ranges also. It's main recommendations for `yuv420p` (https://en.wikipedia.org/wiki/YUV) 
- `yuvj420p` like I420, but with a full range ("digital", 0-255) (https://wiki.videolan.org/YUV#J420)

added yuvj420p format for to_ndarray

---

av/container/input.pyx

fix: avoid infinite timeout bug on av.open()

---

av/video/frame.pyx
av/video/plane.pxd
av/video/plane.pyx
tests/test_videoframe.py

- Fixes plane count calculation at `VideoFrame.planes` (in cases when many components are stored in the same plane).
- Corrects the `VideoPlane` constructor so that the palette plane in `pal8` is accessible.
- Implements ndarray conversion with `rgb8` / `bgr8`.
- Implements ndarray conversion with `pal8` (by accepting a `palette` argument / returning a tuple).

Support for more pixel formats

---

.github/workflows/tests.yml

On OS X, the `ssl` module has an issue which breaks the build.

[build] disable macos tests for now

---

av/container/core.pyx
av/container/output.pyx

It's safe to call os.fsencode() regardless of whether the filename was
passed as `bytes` or `str`. Remove shim for `os.fsencode()`, it has been
available since Python 3.2.

Use os.fsencode for both input and output file names (fixes: #600)

---

AUTHORS.py
HACKING.rst
av/__main__.py
av/audio/layout.pyx
av/codec/context.pyx
av/container/core.pyx
av/container/output.pyx
av/enum.pyx
av/error.pyx
av/filter/filter.pyx
av/filter/graph.pyx
av/stream.pyx
av/utils.pxd
av/utils.pyx
docs/conf.py
docs/development/includes.py
docs/generate-tagfile
scratchpad/glproxy.py
scripts/activate.sh
scripts/autolint
scripts/clean-branches
setup.py
tests/test_container.py
tests/test_doctests.py
tests/test_timeout.py

Also simplify the `dict_to_avdict` signature as we:
- always pass `clear=True`
- always explicitly pass the `encoding` and `errors` arguments

Remove some references to Python 2

---

.github/workflows/tests.yml
av/audio/resampler.pyx
av/buffer.pyx
av/bytesource.pyx
av/codec/__init__.py
av/codec/context.pyx
av/container/core.pyx
av/container/input.pyx
av/container/output.pyx
av/container/pyio.pyx
av/enum.pyx
av/error.pyx
av/frame.pyx
av/logging.pyx
av/sidedata/sidedata.pyx
av/stream.pyx
av/utils.pyx
av/video/codeccontext.pyx
av/video/frame.pyx
av/video/reformatter.pyx
av/video/stream.pyx
scripts/fetch-vendor
scripts/fetch-vendor.json
scripts/test
setup.cfg

Newer cibuildwheel versions seem to fail on Windows.

[build] pin cibuildwheel to version 1.4.2

---

av/frame.pyx

This code is probably unused, but the bug is still there

Fix args order in Frame.__repr__

---

av/logging.pyx

The documentation lists `QUIET` as a possible loglevel since 64e80ee.
In that same commit, QUIET was marked as `not actually a level`, however.
Later it was fully removed as a loglevel in 2ee9684.
This pull request / commit fixes the documentation in that regard.

fix docs: loglevel QUIET isn't available

---

examples/numpy/generate_video_with_pts.py

I didn't notice an encoding example that uses PTSes so I thought I'd add one.
I hope I got this right. I realize ffmpeg's notions of time are "implementation-defined", to put it mildly, and PyAV can't hide that in any good way.
- setting `stream.codec_context.time_base`
- setting `frame.pts` calculated from `stream.codec_context.time_base`

example: encoding with custom PTS

---

tests/test_codec_context.py

Updated the test to check against a FATE suite sample as suggested in #750

Update test to check codec tag against known FATE suite sample

---

tests/test_errors.py
tests/test_logging.py

Do not assume that `1 == ENOENT` and `2 == EPERM` (as `OSError`); rather use the `errno` module to get/use their values.

[tests] do not hardcode errno values

---

av/format.pyx
tests/test_containerformat.py

Some formats go by multiple names, so checking for equality of the
format name fails. Use the higher-level `av_guess_format` which does
the right thing.

Use av_guess_format for output container format (fixes: #691)

---

av/codec/context.pxd
av/codec/context.pyx
include/libavcodec/avcodec.pxd
include/libavutil/avutil.pxd
tests/test_codec_context.py

- this member can only be set for decoders
- we need to allocate and free the memory

Fix setting CodecContext.extradata

---

av/audio/__init__.py

Currently `AudioStream` needs to be imported from `av.audio.stream` since it's missing from `av.audio.__init__`.
I noticed that `av.video.__init__` exports `VideoStream`, so doing the same for `AudioStream` seems logical.
https://github.com/PyAV-Org/PyAV/blob/main/av/video/__init__.py

Export ``AudioStream`` in ``av.audio.__init__``

---

av/container/core.pyx

libavformat seems to set its own default values, see:
https://github.com/FFmpeg/FFmpeg/blob/8ff3fbf6bca0ee897e458fc27e5f967cdcbc16c7/libavformat/demux.c#L2393

Do not set max_analyze_duration at container init (fixes #801)

---

docs/overview/about.rst

PyAV v8.0.3 ships with FFMPEG 4.3.1, which should be reflected in the documentation.

Reflect the updated FFMPEG version in docs

---

av/video/codeccontext.pyx
av/video/format.pxd
av/video/format.pyx
av/video/frame.pyx
tests/test_codec_context.py
tests/test_videoformat.py
tests/test_videoframe.py

Fixes #815.
I implemented a `get_pix_fmt` wrapper that calls and checks the return value of `av_get_pix_fmt` and raises an appropriate exception.

Harden pix_fmt

---

av/video/frame.pyx
tests/test_videoframe.py

If the user passes height / width to VideoFrame.to_image(), the
output of reformat() may have a different size than the original
frame, so we cannot rely on `self.height` or `self.width`.

Fix VideoFrame.to_image with height & width (fixes #878)

---

av/codec/context.pyx
av/container/input.pyx
av/container/output.pyx
av/packet.pxd
av/packet.pyx
av/stream.pyx
av/subtitles/codeccontext.pyx
include/libavcodec/avcodec.pxd

[`av_init_packet` is deprecated as of FFmpeg 4.4](https://github.com/FFmpeg/FFmpeg/blob/9a194252c78c74c4455f837fd152b61904f5dc85/doc/APIchanges#L224). This PR replaces `av_init_packet` with `av_packet_alloc` and uses `av_packet_free` to both free the `AVPacket` and clear the `AVPacket*` (The replacement functions [have been available since FFmpeg 3.0](https://github.com/FFmpeg/FFmpeg/blob/9a194252c78c74c4455f837fd152b61904f5dc85/doc/APIchanges#L1125)).

Replace deprecated av_init_packet with av_packet_alloc

---

av/stream.pxd
av/stream.pyx
tests/test_encode.py

In contrast to `__getattr__`, `__setattr__` [doesn't check the existing attributes](https://docs.python.org/3/reference/datamodel.html#object.__getattr__) first. This causes the `Stream.time_base` setter to never get called. This PR moves the `Stream.time_base` setter into `Stream.__setattr__`, and this should fix #784.

Fix setting Stream time_base (fixes #784)

---

av/filter/context.pyx
av/filter/graph.pyx
tests/test_filters.py

PyAV frames didn't have a `time_base` after they were passed through a filter and `add_buffer` also ignored the `time_base`.
The following example deinterlaces a 30fps video.
```python
import av.filter
import errno
input_container = av.open(format='lavfi', file='color=c=pink:duration=5:r=30')
input_video_stream = input_container.streams.video[0]
graph = av.filter.Graph()
buffer = graph.add_buffer(template=input_video_stream)
bwdif = graph.add("bwdif", "send_field:tff:all")
buffersink = graph.add("buffersink")
buffer.link_to(bwdif)
bwdif.link_to(buffersink)
graph.configure()
for frame in input_container.decode():
print(f"old time_base: {frame.time_base}, old pts: {frame.pts}")
graph.push(frame)
while True:
try:
filtered_frame = graph.pull()
except av.utils.AVError as e:
if e.errno != …
```

Better time_base support with filters

---

av/audio/codeccontext.pyx
av/audio/resampler.pxd
av/audio/resampler.pyx
include/libavfilter/avfilter.pxd
tests/test_audioresampler.py
tests/test_codec_context.py
tests/test_encode.py

The pyav resampler and the fifo can't handle any pts inconsistencies, but ffmpeg can. If we take a look at the ffmpeg tool we can see that the heavy lifting for the resampling is done by the aformat filter (https://github.com/FFmpeg/FFmpeg/blob/169259d9a381a3c2132672da5c5f250fa194fb4d/fftools/ffmpeg_filter.c#L607). The fifo is implemented by the the buffersink (https://github.com/FFmpeg/FFmpeg/blob/169259d9a381a3c2132672da5c5f250fa194fb4d/fftools/ffmpeg_filter.c#L1113).
This PR to matches the pyav resampler behavior to the ffmpeg tool by using the same filters. This also simplifies the code quite a bit. 
Fixes #761
Depends on #765

Rework resampler and fifo to match ffmpeg behavior

---

av/audio/frame.pyx
av/utils.pxd
av/utils.pyx
av/video/frame.pyx
tests/test_audioframe.py

We assumed that sample data is always stored in little-endian order, but
that is not the case according to the FFmpeg documentation:
The data described by the sample format is always in native-endian order.

[audio frame] fix ndarray conversion endianness (fixes: #833)

---

av/filter/context.pyx
av/filter/graph.pyx
tests/test_filters.py

Closes: #886 
This PR adds the ability to send EOF by pushing None on a video `buffer` as proposed in #886 
@jlaine I don't know if you have a preferred code style for the repo, so I didn't apply anything. Let me know if this needs more additions from your side or what is missing to make this complete :)

Enable sending EOF to Graphs

---

av/audio/codeccontext.pxd
av/audio/codeccontext.pyx
av/audio/resampler.pxd
av/audio/resampler.pyx
tests/test_audioresampler.py

In the previous behaviour it was only possible to perform flushing for a
"passthrough" resampler, dropping the final frames if actual resampling
was required.

[audio] make resampler consistently flush buffer

---

av/audio/frame.pyx
av/stream.pyx
av/video/frame.pyx
tests/test_audioframe.py
tests/test_seek.py
tests/test_videoframe.py

The following deprecated methods are removed:
- AudioFrame.to_nd_array
- VideoFrame.to_nd_array
- Stream.seek

Remove deprecated methods

---

av/audio/stream.pyx
av/stream.pyx
av/video/stream.pxd
av/video/stream.pyx

- the `average_rate` is already defined on the base Stream class, we do
not need to redefine it in VideoStream
- prune unused imports from AudioStream and VideoStream
- fix a typo in the `guessed_rate` docstring

[streams] prune some dead code

---

tests/test_subtitles.py
tests/test_videoframe.py

We *know* we are using Python 3, so drop the tests using buffer() and
always run those using memoryview().

[tests] explicitly run memoryview() tests

---

av/audio/format.pyx
av/audio/stream.pyx
av/container/input.pyx
tests/test_decode.py
tests/test_file_probing.py

- make get_audio_format() return None for invalid formats
- fix AudioStream.__repr__ to deal with this situation

Ensure probing a corrupt file does not crash (fixes: #590)

---

scripts/fetch-vendor.json

- VPX is enabled on all platforms
- the Windows build disable mediafoundation support as it drags in a
dependency on MFPlat.DLL

[package] update FFmpeg binaries

---

av/enum.pyx
av/sidedata/sidedata.pyx
include/libavcodec/avcodec.pxd

Hi,
I'm interested in solving #723, but since it relies on a FFmpeg >= 4.4 feature, I am not sure how to proceed to avoid breaking builds relying on older versions.
Still, with a FFmpeg 4.4 build from source + this patch, I was able to retrieve the SEI side data.

Support AV_FRAME_DATA_SEI_UNREGISTERED (fixes: #723)

---

av/container/output.pxd
av/container/output.pyx

https://github.com/PyAV-Org/PyAV/pull/872 seems to have introduced a memory leak as the packet that is allocated in `mux_one` is not freed. This PR adds a packet_ptr to the OutputContainer which follows the OutputContainer's lifecycle and is freed in its `__dealloc__`.

Free packet used for muxing in OutputContainer

---

av/codec/context.pyx
docs/api/time.rst
tests/test_codec_context.py
tests/test_decode.py

The FFmpeg API docs state that using AVCodecContext.time_base for
decoders is deprecated and AVCodecContext.framerate should be used
instead.

[codec context] deprecate CodecContext.time_base for decoders

---

av/video/frame.pyx
tests/test_videoframe.py

This fix the function useful_array when unaligned and dtype's size is 2 or more bytes. See the added test that fails with previous' function.
The issue is that the current fonction crops the numpy array using sizes in bytes instead of in number of array elements. When dtype is not a byte, the wrong cropping occurs.
There are several way to fix the function, such as expressing `total_line_size` and `useful_line_size` in number of elements instead of bytes. I choose to crop the numpy array in bytes before reinterpreting it in `dtype`.

Fix useful_array when unaligned and dtype > 1 byte

---

av/video/frame.pyx
tests/test_videoframe.py

This adds support for gbrp, gbrp10le, gbrp12le, gbrp14le, gbrp16le and their big-endian counterpart formats.
If this PR is ok, I will also add support in the near future for yuv444p, yuv422p and gbrp32f formats.
This can be tested using the following script (doesn't work for 14 & 16 bits)
```python
import numpy as np
import av
WIDTH = 1920
HEIGHT = 1080
BIT_DEPTH = 12
if BIT_DEPTH == 8:
pix_fmt = "gbrp"
dtype = np.uint8
else:
pix_fmt = f"gbrp{BIT_DEPTH}le"
dtype = np.uint16
ocntnr = av.open("test.mp4", "w")
ovstrm = ocntnr.add_stream("av1")
ovstrm.width = WIDTH
ovstrm.height = HEIGHT
ovstrm.pix_fmt = pix_fmt
max = 2**BIT_DEPTH - 1
gradient = np.repeat(np.arange(WIDTH) / WIDTH, 3)
h = np.round(np.linspace(0, HEIGHT, 9, endpoint=True)).astype(np.uint32)
colours = [
[max, max, max],  # White …
```

Add support in VideoFrame ndarray for gbrp formats

---

av/filter/pad.pyx
include/libavfilter/avfilter.pxd

It doesn't seem safe to rely on the return value of `lib.avfilter_pad_get_name()` to iterate. The docs say that it is up to the caller to ensure the index is valid: https://ffmpeg.org/doxygen/trunk/group__lavfi.html#ga2d69631bb24a0a2b7ac0e00fe1dfab3b This seemed to be causing some spurious test errors on some platforms.
Before libavfilter 8.3.100 (ffmpeg < 5.0), the function to use to get the filter count was `avfilter_pad_count`, but that is now deprecated. We can now use either `avfilter_filter_pad_count` or use the `AVFilter.nb_input` (output) fields directly. See https://ffmpeg.org/pipermail/ffmpeg-cvslog/2021-August/128485.html

Use pad count in alloc_filter_pads

---

av/video/frame.pyx
tests/test_videoframe.py

Adds support for floating point RGB format.
Can be tested with this script:
```python
import numpy as np
import av
WIDTH = 1920
HEIGHT = 1080
BIT_DEPTH = 12
if BIT_DEPTH == 8:
pix_fmt = "gbrp"
dtype = np.uint8
else:
pix_fmt = f"gbrp{BIT_DEPTH}le"
dtype = np.uint16
ocntnr = av.open("test.mp4", "w")
ovstrm = ocntnr.add_stream("av1")
ovstrm.width = WIDTH
ovstrm.height = HEIGHT
ovstrm.pix_fmt = pix_fmt
max = 2**BIT_DEPTH - 1
gradient = np.repeat(np.arange(WIDTH) / WIDTH, 3)
h = np.round(np.linspace(0, HEIGHT, 9, endpoint=True)).astype(np.uint32)
colours = [
[max, max, max],  # White
[max, 0, 0],  # Red
[0, max, 0],  # Green
[0, 0, max],  # Blue
[max, max, 0],  # Yellow
[max, 0, max],  # Magenta
[0, max, max],  # Cyan
[0, 0, 0],  # Black
]
array = np.empty((HEIGHT, WIDTH, 3), dtype=dtype)
for …
```

Add support in VideoFrame ndarray for gbrpf32 format

---

setup.py

cibuildwheel v2.10.0 and later will automatically build wheels for Python 3.11.

[package] advertise Python 3.11 support

---

av/stream.pyx
tests/test_codec_context.py
tests/test_decode.py
tests/test_encode.py
tests/test_file_probing.py
tests/test_python_io.py
tests/test_seek.py

The `Stream` class has a confusing behaviour which proxies:
- both codec context *and* codec properties for read access
- only codec context properties for write access
Start simplifying things by completely removing access to codec properties.

Do not pull codec_context.codec properties up to the stream

---

.github/workflows/tests.yml
docs/overview/installation.rst
scripts/fetch-vendor.json

We also update our test matrix to explicitly test against FFmpeg 5.1.

[package] compile wheels against FFmpeg 5.1.2

---

av/stream.pyx
tests/test_file_probing.py

See https://github.com/PyAV-Org/PyAV/issues/1005
Since the behavior of `VideoStream.framerate` has changed, this PR disallows passthrough of that attribute so that users will be forced to switch to `VideoStream.average_rate`

Deprecate Stream.framerate passthrough

---

.github/workflows/tests.yml

This should get rid of the warnings related to Node.js 12 actions.

[tests] update all github actions to latest version

---

scratchpad/audio.py
scratchpad/cctx_encode.py
scratchpad/decode.py
scratchpad/resource_use.py
scratchpad/seekmany.py

As discussed at https://portingguide.readthedocs.io/en/latest/etc.html#raw-buffer-protocol-buffer-and-memoryview `buffer()` was removed in Python 3 in favor of [`memoryview()`](https://docs.python.org/3/library/stdtypes.html#memoryview).

[scratchpad] buffer() was removed in Python 3

---

examples/numpy/generate_video.py

By the time you got to that line, the number is already a uint8, and cannot take any values outside of 0, 255.

Remove unecessary clip in numpy example

---

setup.py

Works toward https://github.com/PyAV-Org/PyAV/issues/1057
You might need to yank the release and release 10.0.1

Add python_requires to help users not install this with python 2

---

av/container/output.pyx
tests/test_encode.py

fixes #1044 
avformat_new_stream(AVFormatContext *s, const AVCodec *c) does not use their second parameter [[1]]
So avcodec_parameters_from_context() should do the job [[2]]
[1]: https://ffmpeg.org/doxygen/trunk/group__lavf__core.html#gadcb0fd3e507d9b58fe78f61f8ad39827
[2]: https://ffmpeg.org/doxygen/trunk/codec__par_8c_source.html#l00099

[streams] populate added stream with codec param (fixes #1044)

---

.github/workflows/tests.yml
av/__main__.py
av/datasets.py
setup.py

Python 3.7 is EOL, let's at least use 3.8 as the minimum.

Update CI/CL, drop Python 3.7

---

av/codec/codec.pyx
av/codec/context.pyx
av/container/core.pyx
include/libavcodec/avcodec.pxd
include/libavformat/avformat.pxd
scripts/activate.sh

Removed and renamed constants with entry from API changes https://git.ffmpeg.org/gitweb/ffmpeg.git/blob/HEAD:/doc/APIchanges
Remove use of AVCodecContext.sub_text_format
2021-09-20 - 176b8d785bf - lavc 59.9.100 - avcodec.h
Deprecate AVCodecContext.sub_text_format and the corresponding
AVOptions. It is unused since the last major bump.
AV_CODEC_CAP_TRUNCATED removed:
2021-09-20 - dd846bc4a91 - lavc 59.8.100 - avcodec.h codec.h
Deprecate AV_CODEC_FLAG_TRUNCATED and AV_CODEC_CAP_TRUNCATED,
as they are redundant with parsers.
AV_CODEC_CAP_AUTO_THREADS renamed to AV_CODEC_CAP_AUTO_THREADS
2021-03-16 - 7d09579190 - lavc 58.132.100 - codec.h
Add AV_CODEC_CAP_OTHER_THREADS as a new name for
AV_CODEC_CAP_AUTO_THREADS. AV_CODEC_CAP_AUTO_THREADS
is now deprecated.
AV_CODEC_CAP_INTRA_ONLY removed …

Update to ffmpeg 6.0

---

.github/workflows/tests.yml
docs/overview/installation.rst
tests/test_doctests.py

We use `av.datasets` so explicitly import it

Fix running doctests

---

examples/basics/parse.py
examples/basics/remux.py
examples/basics/save_keyframes.py
examples/numpy/barcode.py
examples/numpy/generate_video.py
examples/numpy/generate_video_with_pts.py
scripts/test
tests/test_audiofifo.py
tests/test_audioresampler.py
tests/test_codec_context.py
tests/test_decode.py
tests/test_deprecation.py
tests/test_dictionary.py
tests/test_doctests.py
tests/test_encode.py
tests/test_enums.py
tests/test_errors.py
tests/test_filters.py
tests/test_logging.py
tests/test_options.py
tests/test_python_io.py
tests/test_seek.py
tests/test_streams.py
tests/test_subtitles.py
tests/test_videoframe.py

It turns out we weren't actually enforcing black, because we missed the `--check` flag!

Reformat Python code with black, and enforce it in CI

---

av/audio/fifo.pyx
tests/test_audiofifo.py

This change makes debugging state errors easier by describing to the user why the state is incomplete.
Before the change:
```py
>>> AudioFifo()
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "av/audio/fifo.pyx", line 15, in av.audio.fifo.AudioFifo.__repr__
File "av/audio/fifo.pyx", line 183, in av.audio.fifo.AudioFifo.sample_rate.__get__
AttributeError: 'NoneType' object has no attribute 'sample_rate'
```
After the change:
```py
>>> AudioFifo()
<av.AudioFifo uninitialized, use fifo.write(frame), at 0x108719650>
```

Catching AttributeError when repr(fifo) that hasn't had fifo.write(frame) called yet

---

.github/workflows/tests.yml
docs/overview/installation.rst
scripts/fetch-vendor.json

In addition to updating FFmpeg to version 5.1.3, this updates libvpx to fix the CVE-2023-5217 buffer overflow vulnerability.

Update our binaries for FFmpeg 5.1

---

av/container/core.pxd
av/container/core.pyx
av/container/input.pyx
tests/test_decode.py

Calling `close()` on an input container calls `avformat_close_input` which will set the `self.ptr` AVFormatContext pointer to NULL. We need to ensure `self.ptr` is not NULL before using it.
Fixes: #1137

Guard input container properties and methods again use after close

---

av/video/codeccontext.pyx
tests/test_encode.py

Allows an application to control the maximum number of B frames, irrespective of what other settings or preset is used.

Add max_b_frames property to codec context

---

av/frame.pyx
docs/api/time.rst

Fix the doc of the `time` page and `av.frame.Frame.dts` according to https://ffmpeg.org/doxygen/5.1/structAVFrame.html#aa52951f35ec9e303d3dfeb4b3e44248a
Also, is it worth to change `av.frame.Frame.dts` to `av.frame.Frame.pkt_dts` to avoid confusion?

fix the doc about `time`

---

README.md
docs/Makefile
docs/conf.py
docs/overview/installation.rst

Update documentation to what we do now. Point to active url

Acknowledge recent changes in docs

---

av/video/frame.pxd
av/video/frame.pyx
av/video/plane.pxd
av/video/plane.pyx
include/libavutil/avutil.pxd
tests/test_videoframe.py

I know there is some concern about having the memory aligned.
I didn't know if it needed to be aligned to 16 bits, or 16 bytes.
If you know let me know which it is, I can add a check for it. If you don't want to support this, then that is fine too.
Closes: https://github.com/PyAV-Org/PyAV/issues/1060

Create a path toward sharing memory from a numpy buffer

---

pyproject.toml

It used to be an incorrect recommendation in some of the upstream docs. `setuptools` auto-injects it when building wheels and it's unnecessary when building sdist.

Stop using `wheel` as an unconditional build dep

---

av/video/codeccontext.pyx
tests/test_codec_context.py

I tried to write a test for `VideoCodecContext.gop_size.__set__()` and I was surprised to find some inconsistencies. 
When using libx264, one of the GOPs will be 1 frame larger than what it's supposed to be, but only when using one of these GOP sizes: 3, 4, 6, 8, 12, 16, 24, 48. I have no idea why this happens, so for the test I chose a gop_size that didn't cause this issue.
Also, dvvideo and dnxhd will always make every frame a keyframe. Currently when this is detected, the test will skip that iteration. I'm open to other suggestions.

Test for VideoCodecContext.gop_size setter

---

av/codec/context.pyx
tests/test_codec.py
tests/test_codec_context.py

This :type: int `delay` variable is currently inaccessible:
https://github.com/PyAV-Org/PyAV/blob/8e32fe7ed7b83eff27682b4e026e7320cb8dfe1e/include/libavcodec/avcodec.pxd#L192
I assume this is supposed to be a reference to ffmpeg's [AVCodecContext::delay](https://ffmpeg.org/doxygen/6.0/structAVCodecContext.html#a948993adfdfcd64b81dad1151fe50f33).
This PR creates a property `codec_context.delay` which references ffmpeg's `AVCodecContext::delay`.
There is a separate, but similarly named, PyAV property `codec.delay` which is a reference to ffmpeg's [AV_CODEC_CAP_DELAY](https://ffmpeg.org/doxygen/6.0/group__lavc__core.html#ga3f55f5bcfbb12e06c7cb1195028855e6).
We might want to rename one of these properties to prevent confusion.
Since the ffmpeg docs for `AVCodecContext::delay` state "Set by …

Add support for ffmpeg's AVCodecContext::delay

---

av/audio/frame.pyx
av/video/frame.pyx
tests/test_codec_context.py

Created a deprecation warning and a test to catch it. Also, replaced `frame.index` from a previous test I wrote.

Deprecate frame.index

---

av/codec/context.pyx
tests/test_decode.py

Fixes https://github.com/PyAV-Org/PyAV/issues/1280

Check None packet when setting time_base after decode

---

av/descriptor.pyx
av/format.pyx
av/frame.pyx
av/option.pyx
av/packet.pyx
av/stream.pyx

"Showing 24 changed files with 907 additions and 843 deletions."
I doubt that you want this all in one PR, so I broke it up into more manageable chunks.
We currently use a legacy syntax for defining properties in an extension class which has been deprecated since ~2016:
https://cython.readthedocs.io/en/stable/src/userguide/extension_types.html#properties
Switching to the new syntax required moving the property docstrings. Previously, the docstring was placed on the line below the `property` keyword. However, using the new syntax there can not be anything between the decorator and the `def` statement, so the docstring was moved to below the def statement.

Convert Cython extension class properties to decorator syntax part 1 of 4

---

av/audio/codeccontext.pyx
av/audio/fifo.pyx
av/audio/format.pyx
av/audio/frame.pyx
av/audio/layout.pyx

I received this error when running the doctests on the `planar` property in av/audio/format.pyx:
`NameError: name 'Format' is not defined`
It was solved by including this:
`>>> from av import AudioFormat as Format`

Convert Cython extension class properties to decorator syntax part 2 of 4

---

av/data/stream.pyx
av/filter/context.pyx
av/filter/filter.pyx
av/filter/link.pyx
av/filter/pad.pyx
av/subtitles/subtitle.pyx

WyattBlue, I saw a note you made here:
https://github.com/PyAV-Org/PyAV/wiki/TODO-general
"Convert properties to decorator syntax. This will also allow doctest to run on them."
Could you explain what you meant by this? Is doctest incompatible with the old syntax?

Convert deprecated cython extension class properties to new syntax part 3

---

av/codec/codec.pyx
av/codec/context.pyx
av/container/input.pyx
av/video/codeccontext.pyx
av/video/format.pyx
av/video/frame.pyx
av/video/plane.pyx
tests/test_colorspace.py

I had some trouble with the `color_range` property in av/video/codeccontext.pyx and tests/test_colorspace.py.
After my changes, `stream.color_range` now returns `2` instead of `None` and therefore fails the test. I have no idea which one is actually correct.
Here is some additional context which may or may not be related:
1. I get this warning when opening the file used in tests/test_colorspace.py:
`container = av.open(fate_suite("amv/MTV_high_res_320x240_sample_Penguin_Joke_MTV_from_WMV.amv"))`
`WARNING  libav.avi:test_colorspace.py:9 scale/rate is 0/0 which is invalid. (This file has been generated by broken software.)`
2. The `color_range` property in av/video/codeccontext.pyx had unusal syntax. The decorator was used, but so was `__get__` and `__set__`.
3. There are two `color_range` …

Convert deprecated cython extension class properties to new syntax part 4

---

av/video/frame.pyx
av/video/plane.pxd
av/video/plane.pyx

The YUV fastpath did not preserve the underlying byte-order, which causes issues for applications that rely on it.

Partially revert #1061

---

av/audio/codeccontext.pyi
av/audio/format.pyi
av/audio/frame.pyi
av/audio/layout.pyi
av/audio/plane.pyi
av/audio/resampler.pyi
av/audio/stream.pyi

Improve stub in av.audio

---

av/sidedata/motionvectors.pyi
av/sidedata/sidedata.pyi

add missing stub in av.sidedata

---

.github/workflows/tests.yml

The latest 12.0.0 release did not get publish to PyPI successfully, as it was triggered by release instead of tag push. This PR should fix this problem.
btw You might have to manually upload wheels for this release, or recreate release for 12.0.0 wheels to be published...

Fix wheels not published to pypi on release

---

.github/workflows/tests.yml

Continuation of https://github.com/PyAV-Org/PyAV/pull/1341
Wheels did not get push to PyPI again... Should had also change trigger to release published.

Trigger workflow on release publish

---

av/__init__.py
av/bitstream.pxd
av/bitstream.pyi
av/bitstream.pyx
av/packet.pyi
docs/api/bitstream.rst
docs/index.rst
include/libav.pxd
include/libavcodec/bsf.pxd
tests/test_bitstream.py

Loosely based on #565
Additional discussion in #489 
This adds bindings for AVBSFContext (BitStreamFilterContext)
I decided against adding binding for AVBitStreamFilter, because it seems like a little bit useless API. You can't do anything with such object besides creating a new BSF context. (except checking which codecs are supported for that BSF, I guess)
It makes the code simpler and imo easier to maintain. Let me know if this is a mistake and those bindings should be added as well.
I think it makes sense to force BitstreamFilterContext creation through the string parsing API, since that's the only way I can see how to set filter options and also allows things like filter chains, etc. 
Adds tests for 'chomp', 'setts' and 'h264_mp4toannexb' filters. We could also test that filter chains …

Add bitstream filters

---

av/bitstream.pxd
av/bitstream.pyi
av/bitstream.pyx
include/libavcodec/bsf.pxd
tests/test_bitstream.py

Hello again,
This is a little follow-up to PR #1375 and issue #489
I realized and fixed 2 problems with the API as defined previously:
* `par_out` of AVBSFContext stands for output parameters and it contains the codec parameters as modified by the bitfilter. This needs to be exposed so that the user can get the modified codec.
Here's a minimal example that shows example expected usage and why it's useful to separate the input and output arguments:
```
with av.open(input_path, mode='r') as input_av_container:
v_stream = input_av_container.streams.video[0]
with av.open(output_path, 'w') as output_av_container:
out_stream = output_av_container.add_stream(template=v_stream)
filter = av.bitstream.BitStreamFilterContext('h264_mp4toannexb',
in_stream = v_stream, out_stream = out_stream)
for …
```

Bitstream filter API fixes

---

av/codec/context.pxd
av/codec/context.pyi
av/codec/context.pyx
av/container/input.pyx

expose `avcodec_flush_buffers()`
From ffmpeg documentation (https://ffmpeg.org/doxygen/trunk/group__lavc__misc.html#gaf60b0e076f822abcb2700eb601d352a6)
```
void avcodec_flush_buffers	(	AVCodecContext * 	avctx	)	
Reset the internal codec state / flush internal buffers.
Should be called e.g. when seeking or when switching to a different stream.
```
Currently with PyAV the only way to reset the CodecContext state is to call seek on the container. This has the downside that it resets the codecs for ALL the streams. This can be annoying if you are doing more advanced stuff like switching between streams midway but don't want to call seek, selectively decode only some streams based on logic, or have the decoding heads at different points in time for different streams and need to sync them up, …

Expose CodecContext flush_buffers

---

setup.py

pkg-config may be prefixed when cross-compiling

setup.py: use PKG_CONFIG env var to get the pkg-config to use

---

scripts/ffmpeg-6.1.json

This adds support for `webp` and removes X11 libraries which were dragged into the macOs builds.

Update binary FFmpeg build

---

.github/workflows/tests.yml

The behaviour of `actions/upload-artifact` have changed, we now need distinct names for each artifact. This also means adjusting our use of `actions/download-artifact` to collect all artifacts.

Update GitHub actions to their latest version

---

.github/workflows/smoke.yml
docs/overview/installation.rst
scripts/ffmpeg-5.0.json
scripts/ffmpeg-5.1.json

This reverts e884e6cd1dac2646fd002b441ca4fdfb2ef818c5.
So far we have not made any changes which justify dropping FFmpeg 5.x, and we do not change the supported platforms in a minor release. We will drop compatibility for FFmpeg 5.x once we switch to the new audio channel API.

Restore tests against FFmpeg 5.x

---

av/video/stream.pyi
av/video/stream.pyx
include/libavformat/avformat.pxd

When user requests stream's SAR, use the upstream's heuristic function ([`av_guess_sample_aspect_ratio()`](https://github.com/FFmpeg/FFmpeg/commit/9163faecd3cdd93b69ae98605e7f518bd228196e)) to report it.
Resolves: https://github.com/PyAV-Org/PyAV/issues/1267

fix: use `av_guess_sample_aspect_ratio` when reporting stream SAR

---

av/frame.pyi
av/frame.pyx

Expose `av_frame_make_writable()` for `av.Frame`, which ensures that the frame data is writable.
Resolves: #1414

feat: expose `make_writable()` for `av.Frame`

---

av/audio/layout.pyx
tests/test_audiolayout.py
tests/test_codec_context.py

There are several places where `AudioLayout` instances can be created from another instance, for example the `AudioCodecContext.layout` setter, but this variant of the constructor is broken.

Fix `AudioLayout`'s "copy" constructor (fixes: #1434)

---

av/codec/context.pyi

Add type definitions for `options` and `time_base`.

Add type definitions for `CodecContext` properties

---

av/subtitles/subtitle.pxd

Always returned `None`. Appeared to be not implemented correctly. Undocumented in type stubs.

Remove SubtitleSet.packet

---

av/__init__.py
av/utils.pyx
setup.py

Closes #1356, continuation of #717.
Adds the `pxd` files in `./include` to the final package distribution, under `av.include`. This allows to build cython extensions to PyAV by including the folder and calling `cimport av`.
Also added a `get_include` method to retrieve the path to the folder to add to the `include_dirs` in `setup.py`, similar to [numpy](https://numpy.org/doc/stable/reference/generated/numpy.get_include.html).

Include libav headers in final distribution

---

av/subtitles/subtitle.pyi
av/subtitles/subtitle.pyx
tests/test_subtitles.py

AssSubtitle is used even for non ASS/SSA formats. These changes make that more obvious to users. FFmpeg does not export ass_split.h, so the dialogue getter is implemented directly in Cython.

Remove TextSubtitle, add dialogue property

---

av/video/reformatter.pyx

The behavior of the VideoReformatter.format() is inconsistent with the documentation. According to the documentation, when color_range is None, it should use the color_range of the frame. However, in the function implementation, the default is set to 0.

fix: set default color range for VideoReformatter.format()

---

av/subtitles/stream.pxd
av/subtitles/stream.pyi
av/subtitles/stream.pyx
tests/test_subtitles.py

Implement proper flushing mechanism when using `avcodec_decode_subtitle2`.
Closes: #1454

flushing subtitle decoder requires a new uninitialized packet

---

av/video/frame.pyi
av/video/frame.pyx

This pull request introduces a new feature to the `VideoFrame` class, allowing the creation of a `VideoFrame` object directly from byte data. With the new `from_bytes` method, it's possible to build a frame without the need for an intermediate converter like `PIL` or `NumPy`.
- Added `from_bytes` method: Allows creating a `VideoFrame` from bytes, specifying width, height, image format, and options for horizontal and vertical flipping.
- Refactored `copy_array_to_plane` function: Updated to call a new helper function, `copy_bytes_to_plane`, which handles byte copying with support for flipping.
These changes remove the need for intermediate converters, such as `PIL` or `NumPy`, streamlining the process of creating video frames directly from bytes. The implementation supports the `"rgba"` …

Add support for creating `VideoFrame` directly from bytes (`from_bytes`)

---

README.md

GH Discussions support upvoting threads and upvoting. Features lacking in Gitter. Gitter is also less activate.

Use GitHub Discussions over Gitter

---

include/libavformat/avformat.pxd

Otherwise llvm 17 complains
```
_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/include/python3.11 -c src/av/container/pyio.c -o build/temp.macosx-10.9-x86_64-cpython-311/src/av/container/pyio.o
src/av/container/pyio.c:3329:157: error: incompatible function pointer types passing 'int (void *, const uint8_t *, int)' (aka 'int (void *, const unsigned char *, int)') to parameter of type 'int (*)(void *, uint8_t *, int)' (aka 'int (*)(void *, unsigned char *, int)') [-Wincompatible-function-pointer-types]
3329 |   __pyx_v_self->iocontext = avio_alloc_context(__pyx_v_self->buffer, __pyx_t_9, __pyx_t_10, ((void *)__pyx_v_self), …
```

Declare write_packet function as const

---

av/codec/context.pyx
av/container/output.pyx
tests/test_codec_context.py

I dug into the [issue I was having with using `time_base` with `add_stream`](https://github.com/PyAV-Org/PyAV/discussions/1525) and the issue was that I was using an encoder so I could specify `extradata`, but in hindsight, that was a problematic workaround and not a real solution. This PR allows setting `extradata` with an encoder, so I can use `libx264` instead of `h264` with `add_stream` so it will work as expected

Allow extradata to be set for encoders

---

av/codec/context.pyx
av/frame.pyx
av/opaque.pxd
av/opaque.pyx
av/packet.pyx
include/libav.pxd
include/libavcodec/avcodec.pxd
include/libavutil/buffer.pxd

Allows tagging AVPackets and AVFrames with any Python object and, when AV_CODEC_FLAG_COPY_OPAQUE is enabled, ffmpeg will take care of propagating the references to those objects from packets -> frames (decoders) and frames -> packets (encoders).
Example usage:
```python
import av
import time
container = av.open("video.mp4")
video_stream = container.streams.video[0]
video_stream.codec_context.copy_opaque = True  # Enable propagating `opaque` from packets to frames
for packet_idx, packet in enumerate(container.demux()):
packet.opaque = (time.time(), packet_idx)  # Could be any Python object (dataclass, str, float, etc)
frames = packet.decode()
print(f"Packet #{packet_idx} yielded {len(frames)} frames")
for frame in frames:
print(f"Decoded frame with opaque={frame.opaque}")
```

feat: expose opaque and opaque_ref

---

av/__init__.py
av/_core.pyi
av/_core.pyx
include/libavutil/avutil.pxd
scripts/test

I'm not sure how you feel about this, but I can't really keep track of all the different version of ffmpeg internal libraries. the "friendly name" is really useful to know.
Let me know what you think.
* For ffmpeg 6.1.2. this returns "6.1.2"
* For ffmpeg 7(.0.0) this returns "7.0"
* For ffmpeg 7.0.2 this returns "7.0.2"
* For ffmpeg 7.1(.0) this returns "7.1"
I find the alignment with the branding much easier to communicate across developers.

Add ffmpeg version info

---

Makefile

A quick search in GCC source code show that `-Wno-incompatible-function-pointer-types` does not exist as a flag. However, there is the close flag `-Wno-incompatible-pointer-types`

CFLAGS in Makefile does not exist

---

av/container/output.pyi
av/container/output.pyx

Additionally, only allow audio stream `rate` to be `int | None`

Disallow `rate` arg to be a float

---

av/audio/stream.pyi
av/codec/context.pxd
av/codec/context.pyi
av/codec/context.pyx
av/container/output.pyx
av/video/stream.pyi
tests/test_streams.py

Use `del` instead. This fixes many null pointer dereferences.

Remove `CodecContext.close()`

---

CHANGELOG.rst
av/container/output.pyi
av/container/output.pyx

Use `add_stream_from_template()` as a replacement. This untested argument makes writing type stubs more complex than it needs to.

Remove `template` arg

---

av/video/codeccontext.pyi
av/video/codeccontext.pyx
tests/test_encode.py

Allows applications to control the min and max quantisers used for encoding.
Also add a test to ensure the encoder is behaving as we expect.
(Just to explain the context here a bit, we're making much more use of PyAV in our standard Raspberry Pi software, so hopefully this will generate quite a few new users. I'm keen to get the tweaks and small new features on our fork back onto mainline here, because that's better for everyone, so there will probably be "a few" small pull requests like this. Thanks!)

Add qmin and qmax parameters to the codec context

---

av/codec/context.pyi
av/codec/context.pyx
av/stream.pyi
av/stream.pyx
include/libavcodec/avcodec.pxd
tests/test_encode.py

The `profile` can now be set as well as queried, so that applications can now encode using different profiles. I've also added a `profiles` property so that applications have a reasonable way to see what profiles exist, and to choose the correct profile name.
There's also a small new encoder test which checks we can set the codec profile and see it change.
There's one point to note with this change:
As far as I can tell, the list of available profiles has moved from the `AVCodec` object to the `AVCodecDescriptor`. I haven't been able to find anything written about this, but it seems to me that, in recent versions of FFmpeg, the `AVCodec` profiles are often empty, and the use of this field may be deprecated.
Again, as far as I can tell, fetching them from the `AVCodecDescriptor` seems to …

Allow the profile of a codec to be set as well as queried

---

av/stream.pxd
av/stream.pyi
av/stream.pyx

`AVStream.side_data` has been removed in #1570 so I think the type stubs and other leftovers from #1249 should be removed as well.
I didn't delete [`AVPacketSideDataType`](https://github.com/PyAV-Org/PyAV/blob/bf03325c967e6102e26734dcde813902e32b977a/include/libavcodec/avcodec.pxd#L300-L338) because maybe we'd like to add this back to [`AvPacket.side_data`](https://ffmpeg.org/doxygen/trunk/structAVPacket.html#ac55bfef91c33f02704ba76518d0f294c) to match the upstream FFmpeg API.

Cleanup `AVStream.side_data` leftovers

---

av/audio/resampler.pyx

This will misbehave if self.graph is None and frame is not None.

Change the raise condition in resampler

---

scripts/build-deps

$PYAV_LIBRARY_ROOT should be created before calling cd $PYAV_LIBRARY_ROOT if building with NVIDIA Codec support.

PYAV_LIBRARY_ROOT: make directory before change directory

---

av/codec/hwaccel.pxd
av/codec/hwaccel.pyi
av/codec/hwaccel.pyx

`AV_HWDEVICE_TYPE_CUDA` supports [`AV_CUDA_USE_CURRENT_CONTEXT`](https://chromium.googlesource.com/chromium/third_party/ffmpeg/+/refs/heads/master/libavutil/hwcontext_cuda.h#68) flag to re-use an exising CUDA context of the application, reducing vram usage when other CUDA kernels are used.

Add support for external flags in hwaccel

---

av/video/format.pyi
av/video/format.pyx
av/video/frame.pyx

This PR extends support for Bayer pixel formats in `VideoFrame`.
The enhancement makes it easier to work with Bayer formatted data in computer vision and video processing workflows.
- Create Bayer `VideoFrame` from `ndarray` or `bytes`
- Convert Bayer `VideoFrame` to  `ndarray`
- Check if a `VideoFormat` is a Bayer-like with its `is_bayer` property
| 8-bit            | 16-bit (little-endian) | 16-bit  (big-endian) |
|-----------------|----------------------------|---------------------------|
| `bayer_bggr8`  | `bayer_bggr16le`           | `bayer_bggr16be`         |
| `bayer_rggb8`  | `bayer_rggb16le`           | `bayer_rggb16be`         |
| `bayer_gbrg8`  | `bayer_gbrg16le`           | `bayer_gbrg16be`         |
| `bayer_grbg8`  | `bayer_grbg16le`           | `bayer_grbg16be`         |

add Bayer pixel formats

---

.github/workflows/tests.yml
MANIFEST.in
README.md
pyproject.toml
setup.py

sdist takes ~4MB of space, is neglected by PyPA, and is a bad experience for both the developer and the user. PyAV does not have universal support for every arch, and removing source builds in PyPI does not change that.

Stop publishing sdist

---

.github/workflows/tests.yml
MANIFEST.in
README.md
docs/overview/installation.rst

@jlaine and @hmaarrfk are responsible for maintaining this format.

Re-add publishing the sdist

---

av/error.pyx

As described in https://github.com/PyAV-Org/PyAV/discussions/1750.

Use Python 3 compatible stderr logging in Cython

---

av/video/frame.pyx
tests/test_videoframe.py

Using this PR as reference: https://github.com/PyAV-Org/PyAV/pull/1767

Add `yuv420p10le` pix_fmt

---

pyproject.toml

Followup to https://github.com/PyAV-Org/PyAV/pull/1860
Support for PEP 639 was only added in setuptools `v77`.

Bump setuptools requirement for PEP 639 support

---

av/video/frame.pyx
tests/test_videoframe.py

extend `supported_np_pix_fmts` pixel formats with `bgr48be, bgr48le, bgra64be, bgra64le`
add handling for `argb, abgr, grayf32le, grayf32be` pixel formats

added BGR48, BGRA64 pixel formats

---

av/frame.pyi
av/frame.pyx
av/video/frame.pyi
include/libavcodec/avcodec.pxd
tests/test_videoframe.py

This PR exposes the [duration](https://ffmpeg.org/doxygen/trunk/structAVFrame.html#ab90bd20a44c79c144045916b00c50e0d ) field on frame objects as the time that a given frame should be displayed for in `time_base` units. 
This can simplify certain decode loops which are searching for specific frames in time, e.g.: 
```
for frame in container.decode(video=0):
if (frame.pts <= target_time_pts <= frame.pts + frame.duration):
break # Found it
```
In this example the frame might not occur *at* the target pts so we need to use duration to check if the frame would be onscreen at the target time.
Currently this can be done by computing an average frame duration using the average frame rate (which is error prone) or trying to synchronize to the packets duration field.

Expose the Duration Field for Frames

---

scripts/ffmpeg-7.1.json

libvpx 1.14.0 is vulnerable to CVE-2024-5197.
libxml2 2.9.13 is vulnerable to CVE-2022-2309, CVE-2023-29469, CVE-2017-5130, CVE-2023-45322, CVE-2024-25062, CVE-2022-40303, CVE-2022-40304, CVE-2023-28484, CVE-2022-29824
Fixes: #1892
Fixes: #1894

Update FFmpeg build to use libvpx 1.15.1 and libxml2 2.14.3

---

av/container/output.pxd
av/container/output.py

This also syncs the QoL changes I've made in basswood-av. "Pure" stands for Cython's "Pure Python" mode, a way to write Cython in the Python grammar.

Make container/output pure

---

av/container/output.py
tests/test_remux.py

Copy template flags if creating a new Codec object

---

tests/test_timeout.py

On my ARM machine, building pyav fails cause the timeout tests fail. Got a docker-proxy listening on 8002
those tests fail with error
```Python
OSError: [Errno 98] Address already in use
```
This change will try a port not used until one is found and won't error anymore

Find available port for timeout tests

---

.github/workflows/smoke.yml

While looking over the config for #1956 I noticed you're installing an old Cython alpha release and probably just want to install either nightlies or the newest release.
This installs the newest release from conda-forge.
Cython ships nightlies to the scientific-python repo: https://anaconda.org/scientific-python-nightly-wheels/cython

Install cython from conda-forge in smoke tests

---

av/video/frame.py

When updating the content of a video, this is more efficient because the existing frame can be used

Add set_image for updating the image content of an existing frame

---

.github/workflows/tests.yml

Build is failing because it can't find libcurl:
ValueError: Cannot repair wheel, because required library "libssl.so.10" could not be located
Someone who cares about this can fix it

Don't build i686 binaries
